[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "interf_data_analysis"
version = "0.1.0"
readme = "README.md"

dependencies = [
"astropy",
"numpy",
"interferopy",
"pandas"
]