[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "interf_data_analysis"
version = "0.0.3"
readme = "README.md"

dependencies = [
"sjmm_util",
"astropy",
"numpy",
"interferopy",
"pandas"
]